name: TinyImageNet
save_dir: saved/
seed: 9
target_device: cuda

arch:
  type: TinyImageNet_ResNet18
  args: {}

transforms:
  type: TinyImageNetAlbumentations
  args: {}

data_loader:
  type: TinyImageNetDataLoader
  args:
    batch_size: 256
    data_dir: data/
    nworkers: 4
    shuffle: True

criterion: cross_entropy_loss

lr_finder:
  epochs: 10

lr_scheduler:
  max_lr_at_epoch: 10
  type: OneCycleLR
  args:
    max_lr: 0.1

optimizer:
  type: SGD
  args:
    lr: 0.001
    momentum: 0.95
    weight_decay: 0.0005

training:
  epochs: 50

